name: 🚀 Deploy site estático via FTP

on:
  push:
    branches:
      - main  

jobs:
  ftp-deploy:
    name: 📂 Deploy direto para Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obter código mais recente
        uses: actions/checkout@v4

      - name: 📤 Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 185.173.111.152
          username: u408447917
          password: Ipps@dm2002
          server-dir: /public_html/
          local-dir: ./